// KOMEK — Complete Translation Object
// Generated with accurate Sorani Kurdish, Farsi and Arabic
// ku = Sorani Kurdish (Iraq/Iran dialect)
// fa = Persian/Farsi (Iran)
// ar = Modern Standard Arabic

const TX = {
  en: {
    nav: { guide: "Guide", letters: "Letters", ask: "Ask", find: "Find" },
    bottomNav: { home: "Home", post: "Post", account: "Account" },
    splash: { tagline: "Your rights · Your language · Your community", getStarted: "Get Started" },
    home: { peopleHelped: "People helped", jobsServices: "Jobs & services", languages: "Languages", letterExplainer: "Letter Explainer", letterExplainerSub: "Upload any official letter — AI explains it in your language", journeyTitle: "Your Journey in the UK", arrive: "Arrive", newToUK: "New to UK", stay: "Stay", leaveToRemain: "Leave to Remain", citizen: "Citizen", citizenship: "Citizenship", community: "Community", jobsServicesCard: "Jobs & Services", availableIn: "Available in", noQuestions: "No questions yet", noListings: "No listings yet" },
    explainer: { heroTitle: "Understand Your Letter", heroSub: "Paste or upload any official letter and we'll explain it in plain language", usesLeft: "uses left today", resetsIn: "Resets in", pasteText: "Paste Text", uploadPhoto: "Upload / Photo", placeholder: "Paste your letter here...", dragDrop: "Drag & drop your letter image or", browse: "browse", takePhoto: "Take Photo", explainBtn: "Explain This Letter", explaining: "Explaining...", letterType: "Letter Type", summary: "Summary", deadlines: "Deadlines", whatToDo: "What To Do", warning: "Warning", limitReached: "Daily limit reached. Come back tomorrow.", errorMsg: "Something went wrong. Please try again.", imageReady: "Image ready — tap Explain", removeImage: "Remove image", createAccount: "Create Free Account", anonImageNote: "3 free image explanations per day without account", anonTextNote: "10 free text explanations per day without account", accountImageNote: "10 image explanations per day", accountTextUnlimited: "Unlimited text explanations", limitImageAnon: "You've used your 3 free image explanations today. Create a free account for 10 per day.", limitTextAnon: "You've used your 10 free text explanations today. Come back tomorrow.", limitImageAccount: "You've used your 10 image explanations today. Come back tomorrow." },
    ask: { heroTitle: "Ask a Question", heroSub: "Get answers from the Komek community and team", placeholder: "What do you want to know?", askBtn: "Ask", posting: "Posting...", awaiting: "Awaiting answer", answered: "Answered", upvote: "Helpful", answerPlaceholder: "Write your answer...", answerBtn: "Post Answer", empty: "No questions yet. Be the first to ask!" },
    post: { heroTitle: "What would you like to post?", heroSub: "Choose a category to get started.", hireStaff: "Hire Staff", hireStaffDesc: "Post a job vacancy", listService: "List a Service", listServiceDesc: "Offer your professional service" },
    hireStaff: { heroTitle: "Post a Job", heroSub: "Find the right person for your role", jobTitle: "Job Title", jobTitlePh: "e.g. Delivery Driver, Chef, Receptionist", description: "Job Description", descPh: "Describe the role and responsibilities...", location: "Location", locationPh: "e.g. London, Birmingham, Manchester", salary: "Salary / Pay", salaryPh: "e.g. £12/hour, £25,000/year, Negotiable", contact: "Contact (Phone or Email)", contactPh: "How should people apply?", submit: "Post Job", submitting: "Posting...", success: "Job posted! It will appear once approved.", required: "Please fill in all fields." },
    listService: { heroTitle: "List a Service", heroSub: "Offer your skills to the Komek community", serviceName: "Service Name", serviceNamePh: "e.g. Plumber, Driving Instructor, Accountant", description: "Description", descPh: "Describe your service and experience...", location: "Location", locationPh: "e.g. London, Birmingham, or Nationwide", price: "Price / Rate", pricePh: "e.g. £50/hour, From £200, Free consultation", contact: "Contact (Phone or Email)", contactPh: "How should people get in touch?", submit: "List My Service", submitting: "Listing...", success: "Service listed! It will appear once approved.", required: "Please fill in all fields." },
    find: { heroTitle: "Find Jobs & Services", heroSub: "Browse opportunities from the Kurdish community", jobs: "Jobs", services: "Services", location: "Location", salary: "Pay", price: "Rate", contact: "Contact", empty: "Nothing here yet.", filled: "Filled", paused: "Paused" },
    account: { heroTitle: "Your Komek Account", heroSub: "Log in or create a free account to post listings.", login: "Log In", signup: "Sign Up", fullName: "Full Name", email: "Email", password: "Password", namePh: "Your full name", passPh: "At least 6 characters", loginBtn: "Log In", signupBtn: "Create Free Account", logout: "Log out", welcome: "Welcome back", postNew: "+ Post a Job or Service", myListings: "My Listings", noListings: "You haven't posted anything yet.", wrongPass: "Incorrect email or password.", noName: "Please enter your name.", cantCreate: "Could not create account.", created: "Account created! You can now log in.", deleteCfm: "Are you sure you want to delete this listing?", pendingNote: "Waiting for admin approval.", edit: "Edit", markFilled: "Mark as Filled", pause: "Pause", unpause: "Unpause", delete: "Delete", saveEdit: "Save & Resubmit", cancel: "Cancel", editNote: "Edit below — listing will need re-approval after saving.", untitled: "Untitled", jobPosting: "Job Posting", service: "Service", approved: "Approved", pending: "Pending", rejected: "Rejected", paused: "Paused", filled: "Filled" },
    guide: { faqTitle: "Common Questions", helpTitle: "Get Help", showAnswer: "Show answer", hideAnswer: "Hide answer", official: "Official", free: "Free" }
  },

  ku: {
    nav: { guide: "ڕێبەر", letters: "نامەکان", ask: "پرسیار", find: "گەڕان" },
    bottomNav: { home: "سەرەکی", post: "بڵاوکردنەوە", account: "ئەکاونت" },
    splash: { tagline: "مافەکانت · زمانەکەت · کۆمەڵگاکەت", getStarted: "دەست پێ بکە" },
    home: { peopleHelped: "کەس یارمەتی دراون", jobsServices: "کار و خزمەتگوزاری", languages: "زمانەکان", letterExplainer: "ڕوونکردنەوەی نامە", letterExplainerSub: "هەر نامەیەکی فەرمی بار بکە — AI بە زمانی خۆت ڕوونی دەکاتەوە", journeyTitle: "گەشتەکەت لە بریتانیا", arrive: "گەیشتن", newToUK: "تازە گەیشتووی", stay: "مانەوە", leaveToRemain: "مۆڵەتی مانەوە", citizen: "هاووڵاتی", citizenship: "هاووڵاتیبوون", community: "کۆمەڵگا", jobsServicesCard: "کار و خزمەتگوزاری", availableIn: "بەردەستە بە", noQuestions: "هێشتا هیچ پرسیارێک نییە", noListings: "هێشتا هیچ لیستێک نییە" },
    explainer: { heroTitle: "نامەکەت تێبگە", heroSub: "نامەی فەرمی بنووسە یان بار بکە، ئێمەش بە زمانێکی ئاسان ڕوونی دەکەینەوە", usesLeft: "جار ئەمڕۆ ماوە", resetsIn: "دەگەڕێتەوە لە", pasteText: "دەقی بنووسە", uploadPhoto: "بار بکە / وێنە", placeholder: "نامەکەت لێرە بنووسە...", dragDrop: "وێنەی نامەکە بکێشە یان", browse: "گەڕان", takePhoto: "وێنە بکە", explainBtn: "نامەکە ڕوون بکەرەوە", explaining: "ڕوونکردنەوە...", letterType: "جۆری نامە", summary: "کورتە", deadlines: "ماوەکان", whatToDo: "چی بکەیت", warning: "ئاگادارکردنەوە", limitReached: "سنووری ڕۆژانە تەواو بوو. سبەی دەگەڕێیتەوە.", errorMsg: "هەڵەیەک ڕوویدا. دووبارە هەوڵ بدەوە.", imageReady: "وێنەکە ئامادەیە — دەست بکە بە ڕوونکردنەوە", removeImage: "وێنەکە بسڕەوە", createAccount: "ئەکاونتی بەخۆڕایی دروست بکە", anonImageNote: "٣ جار ڕوونکردنەوەی وێنە بەخۆڕایی بەبێ ئەکاونت", anonTextNote: "١٠ جار ڕوونکردنەوەی دەق بەخۆڕایی بەبێ ئەکاونت", accountImageNote: "١٠ جار ڕوونکردنەوەی وێنە ڕۆژانە", accountTextUnlimited: "ڕوونکردنەوەی دەقی نامحدود", limitImageAnon: "٣ جارت ڕوونکردنەوەی وێنەی بەخۆڕایی ئەمڕۆ بەکارهێناوە. ئەکاونت دروست بکە بۆ ١٠ جار ڕۆژانە.", limitTextAnon: "١٠ جارت ڕوونکردنەوەی دەقی بەخۆڕایی ئەمڕۆ بەکارهێناوە. سبەی دەگەڕێیتەوە.", limitImageAccount: "١٠ جارت ڕوونکردنەوەی وێنەی ئەمڕۆ بەکارهێناوە. سبەی دەگەڕێیتەوە." },
    ask: { heroTitle: "پرسیار بکە", heroSub: "وەڵام وەربگرە لە تیمی کۆمەڵگای کۆمەک", placeholder: "چیت دەوێ بزانیت؟", askBtn: "بپرسە", posting: "دەنێردرێت...", awaiting: "چاوەڕێی وەڵام", answered: "وەڵامدراوە", upvote: "باشە", answerPlaceholder: "وەڵامەکەت بنووسە...", answerBtn: "وەڵام بنێرە", empty: "هێشتا هیچ پرسیارێک نییە. یەکەمین بە!" },
    post: { heroTitle: "چیت دەوێ بڵاو بکەیتەوە؟", heroSub: "پۆلێک هەڵبژێرە بۆ دەستپێکردن.", hireStaff: "کرێکار بگرە", hireStaffDesc: "ئاگادارکردنەوەی کار بڵاو بکەرەوە", listService: "خزمەتگوزاری تۆمار بکە", listServiceDesc: "خزمەتگوزاری پیشەییەکەت پێشکەش بکە" },
    hireStaff: { heroTitle: "کار بڵاو بکەرەوە", heroSub: "کەسی گونجاو بدۆزەرەوە بۆ شوێنەکەت", jobTitle: "ناونیشانی کار", jobTitlePh: "بۆ نموونە: شۆفێر، ئاشپەز، ڕیسێپشنیست", description: "وەصفی کار", descPh: "کارەکە و بەرپرسیارییەکان وەسف بکە...", location: "شوێن", locationPh: "بۆ نموونە: لەندەن، بێرمینگهام، مانچێستەر", salary: "مووچە", salaryPh: "بۆ نموونە: ١٢ پاوند/کاتژمێر، قابیلی گفتوگۆیە", contact: "پەیوەندی (تەلەفۆن یان ئیمەیل)", contactPh: "چۆن داواکاری بکەن؟", submit: "کار بڵاو بکەرەوە", submitting: "دەنێردرێت...", success: "کار بڵاو کرایەوە! دوای پەسەندکردن دەردەکەوێت.", required: "تکایە هەموو خانەکان پڕ بکەرەوە." },
    listService: { heroTitle: "خزمەتگوزاری تۆمار بکە", heroSub: "شارەزاییەکانت پێشکەش بکە بە کۆمەڵگای کۆمەک", serviceName: "ناوی خزمەتگوزاری", serviceNamePh: "بۆ نموونە: بلامبەر، مامۆستای شوفێری، ژمێریار", description: "وەصف", descPh: "خزمەتگوزاری و ئەزموونەکەت وەسف بکە...", location: "شوێن", locationPh: "بۆ نموونە: لەندەن، بێرمینگهام، یان سەرتاسەری بریتانیا", price: "نرخ", pricePh: "بۆ نموونە: ٥٠ پاوند/کاتژمێر، لە ٢٠٠ پاوند، ڕاوێژی بەخۆڕایی", contact: "پەیوەندی (تەلەفۆن یان ئیمەیل)", contactPh: "چۆن پەیوەندیت پێ بکەن؟", submit: "خزمەتگوزاری تۆمار بکە", submitting: "دەنێردرێت...", success: "خزمەتگوزاری تۆمار کرا! دوای پەسەندکردن دەردەکەوێت.", required: "تکایە هەموو خانەکان پڕ بکەرەوە." },
    find: { heroTitle: "کار و خزمەتگوزاری بدۆزەرەوە", heroSub: "دەرفەتەکان لە کۆمەڵگای کوردی گەڕان", jobs: "کارەکان", services: "خزمەتگوزاریەکان", location: "شوێن", salary: "مووچە", price: "نرخ", contact: "پەیوەندی", empty: "هێشتا هیچ نییە.", filled: "پڕکراوە", paused: "وەستاوە" },
    account: { heroTitle: "ئەکاونتی کۆمەکت", heroSub: "بچۆ ژوورەوە یان ئەکاونتی بەخۆڕایی دروست بکە بۆ بڵاوکردنەوەی لیست.", login: "چوونەژوورەوە", signup: "ئەکاونت دروست بکە", fullName: "ناوی تەواو", email: "ئیمەیل", password: "پاسوۆرد", namePh: "ناوی تەواوت", passPh: "کەمەوە ٦ پیت", loginBtn: "چوونەژوورەوە", signupBtn: "ئەکاونتی بەخۆڕایی دروست بکە", logout: "دەرچوون", welcome: "بەخێربێیتەوە", postNew: "+ کار یان خزمەتگوزاری بڵاو بکەرەوە", myListings: "لیستەکانم", noListings: "هێشتا هیچت بڵاو نەکردوەتەوە.", wrongPass: "ئیمەیل یان پاسوۆرد هەڵەیە.", noName: "تکایە ناوت بنووسە.", cantCreate: "نەتوانرا ئەکاونت دروست بکرێت.", created: "ئەکاونت دروست کرا! ئێستا دەتوانیت بچیتە ژوورەوە.", deleteCfm: "دڵنیایت کە دەتەوێت بسڕیتەوە؟", pendingNote: "چاوەڕوانی پەسەندکردنی ئەدمینە.", edit: "دەستکاری", markFilled: "وەک پڕکراو نیشان بدە", pause: "ڕاگرتن", unpause: "دووبارە چالاک بکەرەوە", delete: "سڕینەوە", saveEdit: "پاشەکەوت و دووبارە بنێرە", cancel: "هەڵوەشاندنەوە", editNote: "دەستکاری بکە — دوای پاشەکەوت پەسەند دەکرێتەوە.", untitled: "بێ ناو", jobPosting: "بڵاوکردنەوەی کار", service: "خزمەتگوزاری", approved: "پەسەندکراو", pending: "چاوەڕوانە", rejected: "ڕەتکراوە", paused: "ڕاگیراوە", filled: "پڕکراوە" },
    guide: { faqTitle: "پرسیاری باو", helpTitle: "یارمەتی بخوازە", showAnswer: "وەڵام پیشان بدە", hideAnswer: "شاردنەوە", official: "فەرمی", free: "بەخۆڕایی" }
  },

  fa: {
    nav: { guide: "راهنما", letters: "نامه‌ها", ask: "سوال", find: "جستجو" },
    bottomNav: { home: "خانه", post: "ارسال", account: "حساب" },
    splash: { tagline: "حقوق تو · زبان تو · جامعه تو", getStarted: "شروع کن" },
    home: { peopleHelped: "نفر کمک شده", jobsServices: "شغل و خدمات", languages: "زبان‌ها", letterExplainer: "توضیح نامه", letterExplainerSub: "هر نامه رسمی را آپلود کن — هوش مصنوعی به زبانت توضیح می‌دهد", journeyTitle: "مسیر تو در بریتانیا", arrive: "ورود", newToUK: "تازه رسیدی", stay: "اقامت", leaveToRemain: "اجازه اقامت", citizen: "شهروند", citizenship: "شهروندی", community: "جامعه", jobsServicesCard: "شغل و خدمات", availableIn: "موجود به زبان", noQuestions: "هنوز سوالی نیست", noListings: "هنوز آگهی‌ای نیست" },
    explainer: { heroTitle: "نامه‌ات را بفهم", heroSub: "هر نامه رسمی را بچسبان یا آپلود کن، ما به زبان ساده توضیح می‌دهیم", usesLeft: "بار امروز باقی مانده", resetsIn: "بازنشینی در", pasteText: "متن را بچسبان", uploadPhoto: "آپلود / عکس", placeholder: "نامه‌ات را اینجا بچسبان...", dragDrop: "تصویر نامه را بکش یا", browse: "مرور", takePhoto: "عکس بگیر", explainBtn: "این نامه را توضیح بده", explaining: "در حال توضیح...", letterType: "نوع نامه", summary: "خلاصه", deadlines: "مهلت‌ها", whatToDo: "چه کاری انجام بدی", warning: "هشدار", limitReached: "محدودیت روزانه تمام شد. فردا برگرد.", errorMsg: "مشکلی پیش آمد. دوباره تلاش کن.", imageReady: "تصویر آماده است — توضیح بده", removeImage: "حذف تصویر", createAccount: "حساب رایگان بساز", anonImageNote: "۳ توضیح تصویر رایگان در روز بدون حساب", anonTextNote: "۱۰ توضیح متن رایگان در روز بدون حساب", accountImageNote: "۱۰ توضیح تصویر در روز", accountTextUnlimited: "توضیح متن نامحدود", limitImageAnon: "امروز ۳ توضیح تصویر رایگانت تموم شد. حساب رایگان بساز برای ۱۰ بار در روز.", limitTextAnon: "امروز ۱۰ توضیح متن رایگانت تموم شد. فردا برگرد.", limitImageAccount: "امروز ۱۰ توضیح تصویرت تموم شد. فردا برگرد." },
    ask: { heroTitle: "سوال بپرس", heroSub: "از تیم و جامعه کومک پاسخ بگیر", placeholder: "می‌خوای چی بدانی؟", askBtn: "بپرس", posting: "در حال ارسال...", awaiting: "در انتظار پاسخ", answered: "پاسخ داده شده", upvote: "مفید بود", answerPlaceholder: "پاسخت را بنویس...", answerBtn: "ارسال پاسخ", empty: "هنوز سوالی نیست. اولین باش!" },
    post: { heroTitle: "چی می‌خوای ارسال کنی؟", heroSub: "یک دسته‌بندی انتخاب کن برای شروع.", hireStaff: "استخدام کارمند", hireStaffDesc: "آگهی شغلی ارسال کن", listService: "ثبت خدمت", listServiceDesc: "خدمت حرفه‌ای‌ات را ارائه بده" },
    hireStaff: { heroTitle: "آگهی شغلی بگذار", heroSub: "فرد مناسب برای نقشت پیدا کن", jobTitle: "عنوان شغل", jobTitlePh: "مثلاً: راننده، آشپز، منشی", description: "توضیحات شغل", descPh: "نقش و مسئولیت‌ها را توضیح بده...", location: "موقعیت", locationPh: "مثلاً: لندن، بیرمنگام، منچستر", salary: "حقوق", salaryPh: "مثلاً: ۱۲ پوند/ساعت، قابل مذاکره", contact: "تماس (تلفن یا ایمیل)", contactPh: "چطور درخواست بدهند؟", submit: "انتشار آگهی", submitting: "در حال ارسال...", success: "آگهی ثبت شد! بعد از تأیید نمایش داده می‌شه.", required: "لطفاً همه فیلدها را پر کن." },
    listService: { heroTitle: "خدمت ثبت کن", heroSub: "مهارت‌هایت را به جامعه کومک ارائه بده", serviceName: "نام خدمت", serviceNamePh: "مثلاً: لوله‌کش، مربی رانندگی، حسابدار", description: "توضیحات", descPh: "خدمت و تجربه‌ات را توضیح بده...", location: "موقعیت", locationPh: "مثلاً: لندن، بیرمنگام، یا سراسر بریتانیا", price: "قیمت", pricePh: "مثلاً: ۵۰ پوند/ساعت، از ۲۰۰ پوند، مشاوره رایگان", contact: "تماس (تلفن یا ایمیل)", contactPh: "چطور باهات تماس بگیرند؟", submit: "ثبت خدمت", submitting: "در حال ثبت...", success: "خدمت ثبت شد! بعد از تأیید نمایش داده می‌شه.", required: "لطفاً همه فیلدها را پر کن." },
    find: { heroTitle: "شغل و خدمات پیدا کن", heroSub: "فرصت‌های جامعه کردی را مرور کن", jobs: "مشاغل", services: "خدمات", location: "موقعیت", salary: "حقوق", price: "نرخ", contact: "تماس", empty: "هنوز چیزی نیست.", filled: "پر شده", paused: "متوقف" },
    account: { heroTitle: "حساب کومک تو", heroSub: "وارد شو یا حساب رایگان بساز برای ارسال آگهی.", login: "ورود", signup: "ثبت نام", fullName: "نام کامل", email: "ایمیل", password: "رمز عبور", namePh: "نام کاملت", passPh: "حداقل ۶ کاراکتر", loginBtn: "ورود", signupBtn: "ساختن حساب رایگان", logout: "خروج", welcome: "خوش اومدی", postNew: "+ شغل یا خدمت ارسال کن", myListings: "آگهی‌هام", noListings: "هنوز چیزی ارسال نکردی.", wrongPass: "ایمیل یا رمز عبور اشتباه است.", noName: "لطفاً نامت را وارد کن.", cantCreate: "نمی‌توان حساب ساخت.", created: "حساب ساخته شد! الان می‌تونی وارد بشی.", deleteCfm: "مطمئنی که می‌خوای حذف کنی؟", pendingNote: "در انتظار تأیید مدیر.", edit: "ویرایش", markFilled: "علامت‌گذاری به عنوان پر شده", pause: "توقف", unpause: "از سرگیری", delete: "حذف", saveEdit: "ذخیره و ارسال مجدد", cancel: "لغو", editNote: "ویرایش کن — بعد از ذخیره نیاز به تأیید مجدد داره.", untitled: "بدون عنوان", jobPosting: "آگهی شغلی", service: "خدمت", approved: "تأیید شده", pending: "در انتظار", rejected: "رد شده", paused: "متوقف", filled: "پر شده" },
    guide: { faqTitle: "سوالات رایج", helpTitle: "کمک بگیر", showAnswer: "نمایش پاسخ", hideAnswer: "پنهان", official: "رسمی", free: "رایگان" }
  },

  ar: {
    nav: { guide: "الدليل", letters: "الرسائل", ask: "اسأل", find: "ابحث" },
    bottomNav: { home: "الرئيسية", post: "نشر", account: "الحساب" },
    splash: { tagline: "حقوقك · لغتك · مجتمعك", getStarted: "ابدأ الآن" },
    home: { peopleHelped: "شخص تمت مساعدته", jobsServices: "الوظائف والخدمات", languages: "اللغات", letterExplainer: "شرح الرسالة", letterExplainerSub: "ارفع أي رسالة رسمية — الذكاء الاصطناعي يشرحها بلغتك", journeyTitle: "رحلتك في المملكة المتحدة", arrive: "الوصول", newToUK: "وصلت للتو", stay: "الإقامة", leaveToRemain: "الإذن بالبقاء", citizen: "مواطن", citizenship: "الجنسية", community: "المجتمع", jobsServicesCard: "الوظائف والخدمات", availableIn: "متاح بـ", noQuestions: "لا توجد أسئلة بعد", noListings: "لا توجد إعلانات بعد" },
    explainer: { heroTitle: "افهم رسالتك", heroSub: "الصق أو ارفع أي رسالة رسمية وسنشرحها بلغة بسيطة", usesLeft: "استخدامات متبقية اليوم", resetsIn: "يُعاد الضبط في", pasteText: "الصق النص", uploadPhoto: "رفع / صورة", placeholder: "الصق رسالتك هنا...", dragDrop: "اسحب صورة الرسالة أو", browse: "تصفح", takePhoto: "التقط صورة", explainBtn: "اشرح هذه الرسالة", explaining: "جارٍ الشرح...", letterType: "نوع الرسالة", summary: "الملخص", deadlines: "المواعيد النهائية", whatToDo: "ماذا تفعل", warning: "تحذير", limitReached: "تم الوصول للحد اليومي. ارجع غداً.", errorMsg: "حدث خطأ. حاول مرة أخرى.", imageReady: "الصورة جاهزة — اضغط للشرح", removeImage: "إزالة الصورة", createAccount: "أنشئ حساباً مجانياً", anonImageNote: "٣ شروحات صور مجانية يومياً بدون حساب", anonTextNote: "١٠ شروحات نص مجانية يومياً بدون حساب", accountImageNote: "١٠ شروحات صور يومياً", accountTextUnlimited: "شروحات نص غير محدودة", limitImageAnon: "استخدمت ٣ شروحات الصور المجانية اليوم. أنشئ حساباً مجانياً للحصول على ١٠ يومياً.", limitTextAnon: "استخدمت ١٠ شروحات النص المجانية اليوم. ارجع غداً.", limitImageAccount: "استخدمت ١٠ شروحات الصور اليوم. ارجع غداً." },
    ask: { heroTitle: "اطرح سؤالاً", heroSub: "احصل على إجابات من فريق ومجتمع كومك", placeholder: "ماذا تريد أن تعرف؟", askBtn: "اسأل", posting: "جارٍ النشر...", awaiting: "في انتظار الإجابة", answered: "تمت الإجابة", upvote: "مفيد", answerPlaceholder: "اكتب إجابتك...", answerBtn: "نشر الإجابة", empty: "لا توجد أسئلة بعد. كن الأول!" },
    post: { heroTitle: "ماذا تريد أن تنشر؟", heroSub: "اختر فئة للبدء.", hireStaff: "توظيف موظفين", hireStaffDesc: "انشر وظيفة شاغرة", listService: "إدراج خدمة", listServiceDesc: "قدّم خدمتك المهنية" },
    hireStaff: { heroTitle: "انشر وظيفة", heroSub: "ابحث عن الشخص المناسب لدورك", jobTitle: "المسمى الوظيفي", jobTitlePh: "مثال: سائق، طاهٍ، موظف استقبال", description: "وصف الوظيفة", descPh: "صف الدور والمسؤوليات...", location: "الموقع", locationPh: "مثال: لندن، برمنغهام، مانشستر", salary: "الراتب", salaryPh: "مثال: £١٢/ساعة، قابل للتفاوض", contact: "التواصل (هاتف أو بريد إلكتروني)", contactPh: "كيف يتقدم المتقدمون؟", submit: "نشر الوظيفة", submitting: "جارٍ النشر...", success: "تم نشر الوظيفة! ستظهر بعد الموافقة.", required: "يرجى ملء جميع الحقول." },
    listService: { heroTitle: "أدرج خدمة", heroSub: "قدّم مهاراتك لمجتمع كومك", serviceName: "اسم الخدمة", serviceNamePh: "مثال: سباك، مدرب قيادة، محاسب", description: "الوصف", descPh: "صف خدمتك وخبرتك...", location: "الموقع", locationPh: "مثال: لندن، برمنغهام، أو على مستوى المملكة", price: "السعر", pricePh: "مثال: £٥٠/ساعة، من £٢٠٠، استشارة مجانية", contact: "التواصل (هاتف أو بريد إلكتروني)", contactPh: "كيف يتواصل معك الناس؟", submit: "إدراج الخدمة", submitting: "جارٍ الإدراج...", success: "تم إدراج الخدمة! ستظهر بعد الموافقة.", required: "يرجى ملء جميع الحقول." },
    find: { heroTitle: "ابحث عن وظائف وخدمات", heroSub: "تصفح الفرص من المجتمع الكردي", jobs: "الوظائف", services: "الخدمات", location: "الموقع", salary: "الراتب", price: "السعر", contact: "التواصل", empty: "لا يوجد شيء بعد.", filled: "مكتمل", paused: "موقوف" },
    account: { heroTitle: "حساب كومك الخاص بك", heroSub: "سجّل دخولك أو أنشئ حساباً مجانياً لنشر الإعلانات.", login: "تسجيل الدخول", signup: "إنشاء حساب", fullName: "الاسم الكامل", email: "البريد الإلكتروني", password: "كلمة المرور", namePh: "اسمك الكامل", passPh: "٦ أحرف على الأقل", loginBtn: "تسجيل الدخول", signupBtn: "إنشاء حساب مجاني", logout: "تسجيل الخروج", welcome: "مرحباً بعودتك", postNew: "+ انشر وظيفة أو خدمة", myListings: "إعلاناتي", noListings: "لم تنشر أي شيء بعد.", wrongPass: "البريد الإلكتروني أو كلمة المرور غير صحيحة.", noName: "يرجى إدخال اسمك.", cantCreate: "تعذر إنشاء الحساب.", created: "تم إنشاء الحساب! يمكنك تسجيل الدخول الآن.", deleteCfm: "هل أنت متأكد من الحذف؟", pendingNote: "في انتظار موافقة المشرف.", edit: "تعديل", markFilled: "وضع علامة كمكتمل", pause: "إيقاف مؤقت", unpause: "استئناف", delete: "حذف", saveEdit: "حفظ وإعادة الإرسال", cancel: "إلغاء", editNote: "قم بالتعديل — سيحتاج إلى موافقة جديدة بعد الحفظ.", untitled: "بدون عنوان", jobPosting: "إعلان وظيفة", service: "خدمة", approved: "موافق عليه", pending: "قيد الانتظار", rejected: "مرفوض", paused: "موقوف", filled: "مكتمل" },
    guide: { faqTitle: "أسئلة شائعة", helpTitle: "احصل على مساعدة", showAnswer: "عرض الإجابة", hideAnswer: "إخفاء", official: "رسمي", free: "مجاني" }
  }
}

export default TX